### ISSUE TITLE
Broken links in phase.html

### ISSUE THREAD

**Issue by Ferdzz** [jorisdeguet/4205a5-Android#1]
In the phase1, phase2 and phase3 page, the links under `Utiles -> Aide mémoire HTML` and `Utiles -> Aide mémoire CSS` don't link to anything. I don't know if it's voluntarily done, but the content under that tab isn't the same as anywhere else on the website.

I'd fix it, but due to the nature of the project, I don't know if I can make a PR

**Comment by jorisdeguet** [comment]
Thank for reporting it. Feel free to make pull requests however, this will reflect your contrib.
