### ISSUE TITLE
Mauvais pointage dans phase2.html

### ISSUE THREAD

**Issue by emeraldsanto** [jorisdeguet/4205a5-Android#6]
## Serveur et implémentation du web service

La section est notée sur 8 points mais dans la section pointage les items font 9 points au total.

![image](https://user-images.githubusercontent.com/33291795/48014407-98807e80-e0f4-11e8-8475-314402d805c2.png)

**Comment by jorisdeguet** [comment]
Fixed with commit https://github.com/jorisdeguet/4205a5-Android/commit/2994ea145b62015ab8400a5d9f4f67f35023b783
