### ISSUE TITLE
Lien mort sur la page index.html

### ISSUE THREAD

**Issue by massicottem** [jorisdeguet/4205a5-Android#7]
À la ligne 65 "utils/PC_2018A_420-5A5_Departement-Informatique.docx" devrait être remplacé par "utils/PC_2018A_420-5A5-EM_Departement-Informatique.docx"

**Comment by jorisdeguet** [comment]
Fixed in https://github.com/jorisdeguet/4205a5-Android/commit/dde1c2750ea7844d574618e252d65342fd465adc
