### ISSUE TITLE
Lien mort dans la page de la semaine 11

### ISSUE THREAD

**Issue by massicottem** [jorisdeguet/4205a5-Android#8]
À la ligne 53, "code/progressbar/" devrait possiblement être remplacé par "https://github.com/jorisdeguet/4205a5-Android/tree/master/code/Progress".

**Comment by jorisdeguet** [comment]
Fixed in https://github.com/jorisdeguet/4205a5-Android/commit/dde1c2750ea7844d574618e252d65342fd465adc
