### ISSUE TITLE
Absence de lien vers les exemples dans la page de la semaine 10

### ISSUE THREAD

**Issue by massicottem** [jorisdeguet/4205a5-Android#9]
Aux lignes 65 et 66, les <span> devrait être remplacé par des <a> et leur href devrait possiblement être changés par "https://github.com/jorisdeguet/4205a5-Android/tree/master/code/https" et par "https://github.com/jorisdeguet/4205a5-Android/tree/master/code/cookies".

**Comment by jorisdeguet** [comment]
Fixed in https://github.com/jorisdeguet/4205a5-Android/commit/dde1c2750ea7844d574618e252d65342fd465adc
